export type ProductCategoryKey = "industrial" | "chemical";

const base = import.meta.env.BASE_URL;

export interface Product {
  id: number;
  name: string;
  brand: string;
  model: string;
  categoryKey: ProductCategoryKey;
  category: string;
  spec: string;
  badges: string[];
  desc: string;
  specs: [string, string][];
  image?: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: "FS500 CCD Spark Optical Emission Spectrometer",
    brand: "SOOHOW",
    model: "FS500",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "Desktop CCD OES, 130–800 nm, JJG 768-2005",
    badges: ["BESTSELLER"],
    desc: "FS500 is a desktop CCD-based spark optical emission spectrometer for rapid elemental analysis in metals. Test methods meet JJG 768-2005. Dynamic range from ppm to percent with accuracy better than 1% deviation. Excellent nitrogen and oxygen analysis, high stability, standard sample calibration, and precision temperature/pressure control.",
    specs: [
      ["Test standard", "JJG 768-2005"],
      ["Dynamic range", "ppm – %"],
      ["Accuracy", "Better than 1% deviation"],
      ["N/O analysis", "Excellent nitrogen and oxygen performance"],
      ["Stability", "High stability and reliability"],
      ["Calibration", "High-grade standard sample calibration"],
      ["Temp. / pressure control", "High-precision temperature and pressure control"],
      ["Dimensions (L×W×H)", "930 × 400 × 630 mm"],
      ["Weight", "Approx. 100 kg"],
      ["Diffraction grating", "Holographic, 2700 lines/mm"],
      ["Dispersion rate", "Primary 0.74 nm/mm; secondary 0.37 nm/mm"],
      ["Focal length", "500 mm"],
      ["Spectral range", "130–800 nm (customer-configurable)"],
      ["Sensor", "Single CCD 3648 px (max. 16×3648 px)"],
      ["Optical tracing", "Full automatic optical system tracing"],
      ["Light chamber", "Closed vacuum chamber — dust and stray light shielded"],
      ["Temperature control", "Light room 34 °C ± 0.1 °C"],
      ["Drift compensation", "Special materials to cope with drift"],
      ["Vibration control", "Damped rubber pads in light room"],
      ["Sample capacity", "Open spark table — samples up to 20 kg, various shapes"],
      ["Argon purge", "Low-consumption argon purge spark table"],
      ["Warm-up time", "Static argon purge — heat-up under 5 min"],
      ["Electrodes", "Easy to remove and maintain"],
      ["Safety", "Sample entrainment protection; abnormal placement cannot fire"],
      ["Start-up (cold / hot)", "Cold ≤30 min; hot ≈5 min"],
      ["Standby argon flow", "<60 ml/min"],
      ["Sample adaptors", "Optional adaptors for different sample types"],
    ],
    image: `${base}uskunalar/FS500.png`,
  },
  {
    id: 2,
    name: "FS800 CCD Spark Optical Emission Spectrometer",
    brand: "SOOHOW",
    model: "FS800",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "Floor-standing CCD OES, 1140×900×500 mm, ~155 kg",
    badges: ["NEW"],
    desc: "FS800 is a floor-standing CCD-based spark optical emission spectrometer for industrial metal analysis. Features computer-controlled spark source with semiconductor discharge excitation, multi-channel CCD data acquisition, and WinLab analysis software on Windows.",
    specs: [
      ["Dimensions (L×W×H)", "1140 × 900 × 500 mm"],
      ["Weight", "Approx. 155 kg"],
      ["Spark control", "Automatic PC control; parameters set by test material"],
      ["Discharge excitation", "Semiconductor-controlled; plasma current 1–100 A"],
      ["Parameter protection", "Discharge parameters password-protected"],
      ["Excitation stability", "Stable spark source — unaffected by power supply fluctuations"],
      ["Excitation calibration", "Calibrated and controlled by excitation line and analysis program"],
      ["Analysis time", "15–30 seconds"],
      ["Spark frequency", "20–1000 Hz adjustable (high/low frequency design)"],
      ["Spark duration", "10–10000 µs adjustable"],
      ["Data acquisition", "Microprocessor multi-channel integration and acquisition"],
      ["ADC", "High-speed 16-bit analog-to-digital converter"],
      ["Microcontroller", "ISP Mixed Signal Flash MCU, 100 MHz"],
      ["Data interface", "High-speed USB data transmission"],
      ["CCD modules", "Up to 16 high-performance CCD detection modules (customizable)"],
      ["Software platform", "Windows operating system"],
      ["WinLab software", "Office-style UI; instrument monitoring and self-diagnosis"],
      ["Analysis features", "Simultaneous element and background determination; substrate correction curves"],
      ["Databases", "Spectral line, reference material, and historical databases"],
      ["Calibration tools", "Automatic optical path calibration; curve fitting"],
      ["Power supply", "220 V ±10%, single phase, 50/60 Hz, 10 A, 1.0 kVA"],
      ["Lab environment — temperature", "10–30°C"],
      ["Lab environment — humidity", "20–80% relative humidity"],
    ],
    image: `${base}uskunalar/FS800.png`,
  },
  {
    id: 3,
    name: "FS500S CMOS Spark Optical Emission Spectrometer",
    brand: "SOOHOW",
    model: "FS500S",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "Compact desktop CMOS OES, 130–800 nm",
    badges: ["BESTSELLER"],
    desc: "FS500S is a compact desktop CMOS-based spark optical emission spectrometer for rapid metal analysis. Stable performance, high performance, and compact footprint. Closed vacuum light chamber with full automatic optical tracing.",
    specs: [
      ["Key advantages", "Stable performance · High performance · Compact size"],
      ["Diffraction grating", "Holographic, 2700 lines/mm"],
      ["Dispersion rate", "Primary 0.74 nm/mm; secondary 0.37 nm/mm"],
      ["Focal length", "500 mm"],
      ["Spectral range", "130–800 nm (customer-configurable)"],
      ["Sensor", "Single CMOS 2084 px (max. 12×2084 px)"],
      ["Optical tracing", "Full automatic optical system tracing"],
      ["Light chamber", "Closed vacuum chamber — dust and stray light shielded"],
      ["Temperature control", "Light room 34 °C ± 0.1 °C"],
      ["Drift compensation", "Special materials to cope with drift"],
      ["Vibration control", "Damped rubber pads in light room"],
      ["Contamination control", "Greatly reduces contamination risk in light chamber"],
      ["Sample capacity", "Open spark table — samples up to 20 kg, various shapes"],
      ["Argon purge", "Low-consumption argon purge spark table"],
      ["Warm-up time", "Static argon purge — heat-up under 5 min"],
      ["Electrodes", "Easy to remove and maintain"],
      ["Safety", "Sample entrainment protection; abnormal placement cannot fire"],
      ["Inflation system", "Intelligent tidal flushing; cold start ≤30 min; hot ≈5 min"],
      ["Standby argon flow", "<60 ml/min"],
      ["Sample adaptors", "Optional adaptors for different sample types"],
    ],
    image: `${base}uskunalar/fs500s.png`,
  },
  {
    id: 4,
    name: "FS400 CCD Spark Optical Emission Spectrometer",
    brand: "SOOHOW",
    model: "FS400",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "Compact desktop CCD OES, 170–430 nm",
    badges: [],
    desc: "FS400 is a compact desktop CCD-based spark optical emission spectrometer for metal analysis. Stable performance, high performance, and compact footprint. Closed vacuum light chamber with full automatic optical tracing.",
    specs: [
      ["Key advantages", "Stable performance · High performance · Compact size"],
      ["Diffraction grating", "Holographic, 2700 lines/mm"],
      ["Dispersion rate", "Primary 0.74 nm/mm; secondary 0.37 nm/mm"],
      ["Focal length", "400 mm"],
      ["Spectral range", "170–430 nm (customer-configurable)"],
      ["Detector", "Single CCD 3648 px (max. 16×3648 px)"],
      ["Optical tracing", "Full automatic optical system tracing"],
      ["Light chamber", "Closed vacuum chamber — dust and stray light shielded"],
      ["Temperature control", "Light room 34 °C ± 0.1 °C"],
      ["Drift compensation", "Special materials to cope with drift"],
      ["Vibration control", "Damped rubber pads in light room"],
      ["Contamination control", "Greatly reduces contamination risk in light chamber"],
      ["Sample capacity", "Open spark table — samples up to 20 kg, various shapes"],
      ["Argon purge", "Low-consumption argon purge spark table"],
      ["Warm-up time", "Static argon purge — heat-up under 5 min"],
      ["Electrodes", "Easy to remove and maintain"],
      ["Safety", "Sample entrainment protection; abnormal placement cannot fire"],
      ["Inflation system", "Intelligent tidal flushing; cold start ≤30 min; hot ≈5 min"],
      ["Standby argon flow", "<60 ml/min"],
      ["Sample adaptors", "Optional adaptors for different sample types"],
    ],
    image: `${base}uskunalar/FS400.png`,
  },
  {
    id: 5,
    name: "HCD1000 Hollow Cathode OES",
    brand: "SOOHOW",
    model: "HCD1000",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "Hollow cathode OES, 200–500 nm, GJB 8781.17-2015",
    badges: ["NEW"],
    desc: "HCD1000 hollow cathode optical emission spectrometer for dry analysis of solid metal samples. Detection meets GJB 8781.17-2015. Direct excitation of chips or powder without chemical reagents — safe, eco-friendly, and simple: weigh, excite, and read results on the computer.",
    specs: [
      ["Detection standard", "GJB 8781.17-2015"],
      ["Analysis method", "Dry analysis — solid samples (chips or powder) directly excited"],
      ["Safety & environment", "No flammable, explosive, or harmful gases; no chemical reagents"],
      ["Workflow", "Weigh → excite → computer analysis of sample concentration"],
      ["Element integration", "Element evaporation curve for optimal integration time per element"],
      ["Spectral range", "200–500 nm"],
      ["Optical focal length", "998.8 mm"],
      ["Grating", "2160 gr/mm; dispersion rate 0.47 nm/mm"],
      ["Electrode cooling", "Circulating water cooling with automatic temperature control"],
      ["Light source", "Hollow cathode power supply"],
      ["Constant temperature", "38 ± 0.1 °C"],
      ["Weight", "Approx. 500 kg"],
      ["Dimensions (L×W×H)", "1800 × 1050 × 1245 mm"],
      ["Lab environment", "Temperature 15–25°C; relative humidity ≤75%"],
    ],
    image: `${base}uskunalar/HCD%201000.png`,
  },
  {
    id: 6,
    name: "GDS8000 GD Optical Emission Spectrometer",
    brand: "SOOHOW",
    model: "GD-OES8000",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "GD-OES, 120–800 nm, 48 channels, DC/RF",
    badges: [],
    desc: "GDS8000 glow discharge optical emission spectrometer (GD-OES) for depth-resolved elemental analysis. Low detection limit, layer-by-layer surface profiling, and direct solid-sample analysis in minutes without dissolution. Integrated optical and mechanical design.",
    specs: [
      ["Detection limit", "Low detection limit"],
      ["Surface analysis", "Layer-by-layer sample surface detection"],
      ["Multi-element", "10+ elements per single measurement"],
      ["Analysis speed", "Sample ready in minutes — very fast detection"],
      ["Sample preparation", "Direct solid analysis — no dilution or dissolution"],
      ["Detection range", "Very wide analytical range"],
      ["Design", "Integrated optical and mechanical whole-machine design"],
      ["Model number", "GD-OES8000"],
      ["Functional mode", "DC or RF"],
      ["Wavelength range", "120–800 nm"],
      ["Spectral resolution", "18 pm – 25 pm"],
      ["Depth resolution", "1–2 nm"],
      ["Sputtering rate", ">1 µm/min"],
      ["Deep profiling scope", "1 nm – 200 µm"],
      ["Focal length", "998.8 mm"],
      ["Element channels", "48"],
      ["Detector", "Photomultiplier tube (PMT)"],
    ],
    image: `${base}uskunalar/GDS8000.png`,
  },
  {
    id: 7,
    name: "AU8000 Precious Metal Analyzer",
    brand: "SOOHOW",
    model: "AU8000",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "XRF analyzer, S–U, 24 elements, GB/T 18043-2013",
    badges: ["BESTSELLER"],
    desc: "AU8000 XRF precious metal analyzer meets GB/T 18043-2013. Si-PIN semiconductor detector delivers accuracy far beyond proportional counters for gold, silver, platinum, palladium, copper, zinc, and nickel in gold, platinum, and K-gold jewelry.",
    specs: [
      ["Standard", "GB/T 18043-2013"],
      ["Detector", "Si-PIN semiconductor — superior to proportional counter"],
      ["Elements analyzed", "Au, Ag, Pt, Pd, Cu, Zn, Ni in jewelry alloys"],
      ["X-ray tube", "Long-life stabilized tube"],
      ["Cooling", "Si-PIN electric refrigeration — no liquid nitrogen"],
      ["Sample camera", "Built-in HD camera — real-time observation"],
      ["Signal processing", "Digital pulse processor; fast, accurate"],
      ["Sample chamber", "Single chamber; manual safety cover"],
      ["Security", "Triple security protection mode"],
      ["Software", "Multivariate regression; matrix correction; friendly UI"],
      ["Configuration", "Si-PIN, multi-channel analysis, X-ray tube, HV/LV, collimator, PC & printer"],
      ["Element range", "S–U (sulfur to uranium)"],
      ["Analytical range", "99.99% purity down to ppm"],
      ["Simultaneous elements", "24 elements"],
      ["Best resolution", "149 eV"],
      ["Detection limit", "ppm level"],
      ["Stability / repeatability", "0.05% (content above 96%)"],
      ["Measure time", "60–200 s (adjustable)"],
      ["Sample types", "Powder, solid, liquid"],
      ["Ambient temperature", "15–30°C"],
      ["Input voltage", "AC 220 V ±5 V (stabilized supply recommended)"],
    ],
    image: `${base}uskunalar/AU8000.png`,
  },
  {
    id: 8,
    name: "OIL8000 RDE-OES Elemental Analyzer",
    brand: "SOOHOW",
    model: "OIL8000",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "RDE-OES oil analysis, <1 ppm, <30 s/test",
    badges: [],
    desc: "OIL8000 rotating disc electrode optical emission spectrometer for rapid elemental analysis of lubricating oils and fluids. Meets ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, and HB 20094.1-2012. No sample pre-treatment or chemical reagents required.",
    specs: [
      ["Test standards", "ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, HB 20094.1-2012"],
      ["Optical design", "Ultra-long focal length for excellent resolution"],
      ["Detection accuracy", "High accuracy; detection limit <1 ppm"],
      ["Test speed", "Single test under 30 seconds"],
      ["Ease of use", "Simple operation and maintenance; low training requirements"],
      ["Sample handling", "No pre-treatment; no chemical reagents; safe and eco-friendly"],
      ["Diffraction grating", "Holographic, 2700 lines/mm"],
      ["Focal length", "500 mm"],
      ["Spectral range", "190–800 nm (by grating selection)"],
      ["Data acquisition", "Microprocessor multi-channel integration; 16-bit ADC"],
      ["Microcontroller", "SP Mixed Signal Flash MCU, 100 MHz; high-speed USB"],
      ["Analysis software", "Create/modify analyzers; print up to 100 results with SD/RSD"],
      ["Power supply", "220 V ±10%, single phase, 50/60 Hz, 10 A, 1.5 kVA"],
      ["Dimensions (L×W×H)", "810 × 500 × 675 mm"],
      ["Weight", "Approx. 52 kg"],
    ],
    image: `${base}uskunalar/OIL8000.png`,
  },
  {
    id: 9,
    name: "OIL8000H RDE-OES Elemental Analyzer",
    brand: "SOOHOW",
    model: "OIL8000H",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "RDE-OES, 32 elements, 30 s/test, 0–6000 ppm",
    badges: ["NEW"],
    desc: "OIL8000H rotating disc electrode optical emission spectrometer for oil and lubricant analysis. Meets ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, and HB 20094.1-2012. Direct oil testing in sample cup — no gas, no chemical reagents, no pretreatment.",
    specs: [
      ["Test standards", "ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, HB 20094.1-2012"],
      ["Constant temperature", "38 °C ± 0.1 °C"],
      ["Test time", "30 seconds per sample"],
      ["Elements analyzed", "32 trace elements simultaneously (24 standard, expandable to 32)"],
      ["Detection accuracy", "Limit 1 ppm; repeatability < ±10%"],
      ["Ease of use", "No assist gas or chemical reagents; oil tested directly in cup"],
      ["Power supply", "AC 220 V ±10%, 50–60 Hz"],
      ["Ambient temperature", "0–55 °C"],
      ["Optical structure", "Paschen-Runge; Roland circle device"],
      ["Focal length", "500 mm"],
      ["Spectral range", "190–800 nm"],
      ["Detector", "CCD"],
      ["Measuring range", "0–6000 ppm"],
      ["Dimensions (L×W×H)", "860 × 410 × 620 mm"],
      ["Weight", "Approx. 97 kg"],
    ],
    image: `${base}uskunalar/OIL8000H.png`,
  },
  {
    id: 10,
    name: "PO100 RDE-OES Elemental Analyzer",
    brand: "SOOHOW",
    model: "PO100",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "Portable RDE-OES, <1 ppm, 30 s, 0–6000 ppm",
    badges: [],
    desc: "PO100 compact benchtop RDE-OES for oil analysis with built-in PC and electrode grinder. Patented digital arc source, high-resolution CCD, and Windows analysis software. Ideal for ship environments — no argon or chemical solvents required.",
    specs: [
      ["Test standards", "ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, HB 20094.1-2012"],
      ["Light source", "Patented digital arc; solid-state excitation; constant current"],
      ["Optical system", "High-resolution CCD; 3648 pixels; 8×200 µm pixel size"],
      ["Software", "Windows (7/10+); control, data management, qualitative & quantitative analysis"],
      ["Design", "Benchtop with built-in computer and motor grinder; compact and portable"],
      ["Operating environment", "Short warm-up; high reliability; suitable for ship use"],
      ["Sample handling", "No argon, oxygen, or solvents; oil directly in cup — no pretreatment"],
      ["Connectivity", "Built-in scanner; Bluetooth and RS-485; built-in electrode grinder"],
      ["Power supply", "AC 220 V ±10%, 50–60 Hz"],
      ["Ambient temperature", "0–55 °C"],
      ["Test time", "30 s"],
      ["Optical structure", "Paschen-Runge; Roland circle device"],
      ["Focal length", "500 mm"],
      ["Spectral range", "190–800 nm"],
      ["Detector", "CCD"],
      ["Detection limit", "<1 ppm"],
      ["Elements", "24 standard; expandable to 32"],
      ["Measuring range", "0–6000 ppm"],
      ["Dimensions (L×W×H)", "770 × 360 × 560 mm"],
      ["Weight", "Approx. 53 kg"],
    ],
    image: `${base}uskunalar/PO100.png`,
  },
  {
    id: 11,
    name: "PO200 RDE-OES Elemental Analyzer",
    brand: "SOOHOW",
    model: "PO200",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "RDE-OES, <1 ppm, 30 s, 0–6000 ppm",
    badges: ["BESTSELLER"],
    desc: "PO200 rotating graphite disc electrode optical emission spectrometer for quantitative trace-element analysis in lubricating oils, hydraulic fluids, fuels, greases, and industrial fluids. Used in military, aviation, marine, mining, power, and commercial oil laboratories.",
    specs: [
      ["Principle", "Rotating disc electrode atomic emission spectroscopy (RDE-OES)"],
      ["Subsystems", "Arc excitation supply; disc/rod electrode system; Paschen-Runge optics; CCD measurement; analysis software"],
      ["Applications", "New and used oils, hydraulic oils, gasoline/diesel, heavy oils, greases, antifreeze, industrial water"],
      ["Power supply", "AC 220 V ±10%, 50–60 Hz"],
      ["Ambient temperature", "0–55 °C"],
      ["Test time", "30 s"],
      ["Optical structure", "Paschen-Runge; Rowland circle device"],
      ["Focal length", "500 mm"],
      ["Spectral range", "190–800 nm"],
      ["Detector", "CCD"],
      ["Detection limit", "<1 ppm"],
      ["Elements", "24 standard; expandable to 32"],
      ["Measuring range", "0–6000 ppm"],
      ["Dimensions (L×W×H)", "660 × 360 × 520 mm"],
      ["Weight", "Approx. 64 kg"],
    ],
    image: `${base}uskunalar/PO200.png`,
  },
  {
    id: 12,
    name: "PO300 RDE-OES Elemental Analyzer",
    brand: "SOOHOW",
    model: "PO300",
    categoryKey: "industrial",
    category: "Industrial Measurement",
    spec: "Compact RDE-OES, 400 mm focus, ≤30 s",
    badges: [],
    desc: "PO300 RDE-OES elemental analyzer uses a graphite rotating disc electrode and atomic emission spectroscopy for oil composition analysis. Compact single-station design with built-in PC, printer, and electrode grinder — ideal for shipboard and field laboratories.",
    specs: [
      ["Principle", "Graphite rotating disc electrode atomic emission spectroscopy"],
      ["Subsystems", "Arc excitation supply; electrode system; Paschen-Runge spectrometer; CCD detection; control & software"],
      ["Applications", "Lubricating oils, hydraulic oils, fuels, greases, antifreeze, industrial water, turbine condensate"],
      ["Industries", "Military, aviation, marine, transport, steel, mining, power plants, oil testing labs"],
      ["Test standards", "ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, HB 20094.1-2012"],
      ["Light source", "Patented digital arc; solid-state excitation; constant current"],
      ["Optical system", "High-resolution CCD; 3648 pixels; 8×200 µm pixel size"],
      ["Software", "Windows 7/10+; instrument control, data management, qualitative & quantitative analysis"],
      ["Design", "Built-in computer, printer, and motor grinder; compact and portable"],
      ["Sample handling", "No argon, oxygen, or solvents; oil directly in cup — no pretreatment"],
      ["Detector", "CCD"],
      ["Focal length", "400 mm"],
      ["Spectral range", "190–800 nm"],
      ["Test time", "≤30 s"],
      ["Dimensions (L×W×H)", "550 × 330 × 430 mm"],
    ],
    image: `${base}uskunalar/PO300.png`,
  },
];
