import {
  getProductCategoryKey,
  type ProductCategoryKey,
} from "./productCategories";

export type { ProductCategoryKey };

const base = import.meta.env.BASE_URL;

export interface Product {
  id: number;
  name: string;
  brand: string;
  model: string;
  categoryKey: ProductCategoryKey;
  category: string;
  spec: string;
  badges: string[];
  desc: string;
  specs: [string, string][];
  image?: string;
}

const productCatalog = [
  {
    id: 1,
    name: "FS500 CCD Spark Optical Emission Spectrometer",
    brand: "SOOHOW",
    model: "FS500",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Desktop CCD OES, 130–800 nm, JJG 768-2005",
    badges: ["BESTSELLER"],
    desc: "FS500 is a desktop CCD-based spark optical emission spectrometer for rapid elemental analysis in metals. Test methods meet JJG 768-2005. Dynamic range from ppm to percent with accuracy better than 1% deviation. Excellent nitrogen and oxygen analysis, high stability, standard sample calibration, and precision temperature/pressure control.",
    specs: [
      ["Test standard", "JJG 768-2005"],
      ["Dynamic range", "ppm – %"],
      ["Accuracy", "Better than 1% deviation"],
      ["N/O analysis", "Excellent nitrogen and oxygen performance"],
      ["Stability", "High stability and reliability"],
      ["Calibration", "High-grade standard sample calibration"],
      ["Temp. / pressure control", "High-precision temperature and pressure control"],
      ["Dimensions (L×W×H)", "930 × 400 × 630 mm"],
      ["Weight", "Approx. 100 kg"],
      ["Diffraction grating", "Holographic, 2700 lines/mm"],
      ["Dispersion rate", "Primary 0.74 nm/mm; secondary 0.37 nm/mm"],
      ["Focal length", "500 mm"],
      ["Spectral range", "130–800 nm (customer-configurable)"],
      ["Sensor", "Single CCD 3648 px (max. 16×3648 px)"],
      ["Optical tracing", "Full automatic optical system tracing"],
      ["Light chamber", "Closed vacuum chamber — dust and stray light shielded"],
      ["Temperature control", "Light room 34 °C ± 0.1 °C"],
      ["Drift compensation", "Special materials to cope with drift"],
      ["Vibration control", "Damped rubber pads in light room"],
      ["Sample capacity", "Open spark table — samples up to 20 kg, various shapes"],
      ["Argon purge", "Low-consumption argon purge spark table"],
      ["Warm-up time", "Static argon purge — heat-up under 5 min"],
      ["Electrodes", "Easy to remove and maintain"],
      ["Safety", "Sample entrainment protection; abnormal placement cannot fire"],
      ["Start-up (cold / hot)", "Cold ≤30 min; hot ≈5 min"],
      ["Standby argon flow", "<60 ml/min"],
      ["Sample adaptors", "Optional adaptors for different sample types"],
    ],
    image: `${base}uskunalar/FS500.png`,
  },
  {
    id: 2,
    name: "FS800 CCD Spark Optical Emission Spectrometer",
    brand: "SOOHOW",
    model: "FS800",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Floor-standing CCD OES, 1140×900×500 mm, ~155 kg",
    badges: ["NEW"],
    desc: "FS800 is a floor-standing CCD-based spark optical emission spectrometer for industrial metal analysis. Features computer-controlled spark source with semiconductor discharge excitation, multi-channel CCD data acquisition, and WinLab analysis software on Windows.",
    specs: [
      ["Dimensions (L×W×H)", "1140 × 900 × 500 mm"],
      ["Weight", "Approx. 155 kg"],
      ["Spark control", "Automatic PC control; parameters set by test material"],
      ["Discharge excitation", "Semiconductor-controlled; plasma current 1–100 A"],
      ["Parameter protection", "Discharge parameters password-protected"],
      ["Excitation stability", "Stable spark source — unaffected by power supply fluctuations"],
      ["Excitation calibration", "Calibrated and controlled by excitation line and analysis program"],
      ["Analysis time", "15–30 seconds"],
      ["Spark frequency", "20–1000 Hz adjustable (high/low frequency design)"],
      ["Spark duration", "10–10000 µs adjustable"],
      ["Data acquisition", "Microprocessor multi-channel integration and acquisition"],
      ["ADC", "High-speed 16-bit analog-to-digital converter"],
      ["Microcontroller", "ISP Mixed Signal Flash MCU, 100 MHz"],
      ["Data interface", "High-speed USB data transmission"],
      ["CCD modules", "Up to 16 high-performance CCD detection modules (customizable)"],
      ["Software platform", "Windows operating system"],
      ["WinLab software", "Office-style UI; instrument monitoring and self-diagnosis"],
      ["Analysis features", "Simultaneous element and background determination; substrate correction curves"],
      ["Databases", "Spectral line, reference material, and historical databases"],
      ["Calibration tools", "Automatic optical path calibration; curve fitting"],
      ["Power supply", "220 V ±10%, single phase, 50/60 Hz, 10 A, 1.0 kVA"],
      ["Lab environment — temperature", "10–30°C"],
      ["Lab environment — humidity", "20–80% relative humidity"],
    ],
    image: `${base}uskunalar/FS800.png`,
  },
  {
    id: 3,
    name: "FS500S CMOS Spark Optical Emission Spectrometer",
    brand: "SOOHOW",
    model: "FS500S",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Compact desktop CMOS OES, 130–800 nm",
    badges: ["BESTSELLER"],
    desc: "FS500S is a compact desktop CMOS-based spark optical emission spectrometer for rapid metal analysis. Stable performance, high performance, and compact footprint. Closed vacuum light chamber with full automatic optical tracing.",
    specs: [
      ["Key advantages", "Stable performance · High performance · Compact size"],
      ["Diffraction grating", "Holographic, 2700 lines/mm"],
      ["Dispersion rate", "Primary 0.74 nm/mm; secondary 0.37 nm/mm"],
      ["Focal length", "500 mm"],
      ["Spectral range", "130–800 nm (customer-configurable)"],
      ["Sensor", "Single CMOS 2084 px (max. 12×2084 px)"],
      ["Optical tracing", "Full automatic optical system tracing"],
      ["Light chamber", "Closed vacuum chamber — dust and stray light shielded"],
      ["Temperature control", "Light room 34 °C ± 0.1 °C"],
      ["Drift compensation", "Special materials to cope with drift"],
      ["Vibration control", "Damped rubber pads in light room"],
      ["Contamination control", "Greatly reduces contamination risk in light chamber"],
      ["Sample capacity", "Open spark table — samples up to 20 kg, various shapes"],
      ["Argon purge", "Low-consumption argon purge spark table"],
      ["Warm-up time", "Static argon purge — heat-up under 5 min"],
      ["Electrodes", "Easy to remove and maintain"],
      ["Safety", "Sample entrainment protection; abnormal placement cannot fire"],
      ["Inflation system", "Intelligent tidal flushing; cold start ≤30 min; hot ≈5 min"],
      ["Standby argon flow", "<60 ml/min"],
      ["Sample adaptors", "Optional adaptors for different sample types"],
    ],
    image: `${base}uskunalar/fs500s.png`,
  },
  {
    id: 4,
    name: "FS400 CCD Spark Optical Emission Spectrometer",
    brand: "SOOHOW",
    model: "FS400",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Compact desktop CCD OES, 170–430 nm",
    badges: [],
    desc: "FS400 is a compact desktop CCD-based spark optical emission spectrometer for metal analysis. Stable performance, high performance, and compact footprint. Closed vacuum light chamber with full automatic optical tracing.",
    specs: [
      ["Key advantages", "Stable performance · High performance · Compact size"],
      ["Diffraction grating", "Holographic, 2700 lines/mm"],
      ["Dispersion rate", "Primary 0.74 nm/mm; secondary 0.37 nm/mm"],
      ["Focal length", "400 mm"],
      ["Spectral range", "170–430 nm (customer-configurable)"],
      ["Detector", "Single CCD 3648 px (max. 16×3648 px)"],
      ["Optical tracing", "Full automatic optical system tracing"],
      ["Light chamber", "Closed vacuum chamber — dust and stray light shielded"],
      ["Temperature control", "Light room 34 °C ± 0.1 °C"],
      ["Drift compensation", "Special materials to cope with drift"],
      ["Vibration control", "Damped rubber pads in light room"],
      ["Contamination control", "Greatly reduces contamination risk in light chamber"],
      ["Sample capacity", "Open spark table — samples up to 20 kg, various shapes"],
      ["Argon purge", "Low-consumption argon purge spark table"],
      ["Warm-up time", "Static argon purge — heat-up under 5 min"],
      ["Electrodes", "Easy to remove and maintain"],
      ["Safety", "Sample entrainment protection; abnormal placement cannot fire"],
      ["Inflation system", "Intelligent tidal flushing; cold start ≤30 min; hot ≈5 min"],
      ["Standby argon flow", "<60 ml/min"],
      ["Sample adaptors", "Optional adaptors for different sample types"],
    ],
    image: `${base}uskunalar/FS400.png`,
  },
  {
    id: 5,
    name: "HCD1000 Hollow Cathode OES",
    brand: "SOOHOW",
    model: "HCD1000",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Hollow cathode OES, 200–500 nm, GJB 8781.17-2015",
    badges: ["NEW"],
    desc: "HCD1000 hollow cathode optical emission spectrometer for dry analysis of solid metal samples. Detection meets GJB 8781.17-2015. Direct excitation of chips or powder without chemical reagents — safe, eco-friendly, and simple: weigh, excite, and read results on the computer.",
    specs: [
      ["Detection standard", "GJB 8781.17-2015"],
      ["Analysis method", "Dry analysis — solid samples (chips or powder) directly excited"],
      ["Safety & environment", "No flammable, explosive, or harmful gases; no chemical reagents"],
      ["Workflow", "Weigh → excite → computer analysis of sample concentration"],
      ["Element integration", "Element evaporation curve for optimal integration time per element"],
      ["Spectral range", "200–500 nm"],
      ["Optical focal length", "998.8 mm"],
      ["Grating", "2160 gr/mm; dispersion rate 0.47 nm/mm"],
      ["Electrode cooling", "Circulating water cooling with automatic temperature control"],
      ["Light source", "Hollow cathode power supply"],
      ["Constant temperature", "38 ± 0.1 °C"],
      ["Weight", "Approx. 500 kg"],
      ["Dimensions (L×W×H)", "1800 × 1050 × 1245 mm"],
      ["Lab environment", "Temperature 15–25°C; relative humidity ≤75%"],
    ],
    image: `${base}uskunalar/HCD%201000.png`,
  },
  {
    id: 6,
    name: "GDS8000 GD Optical Emission Spectrometer",
    brand: "SOOHOW",
    model: "GD-OES8000",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "GD-OES, 120–800 nm, 48 channels, DC/RF",
    badges: [],
    desc: "GDS8000 glow discharge optical emission spectrometer (GD-OES) for depth-resolved elemental analysis. Low detection limit, layer-by-layer surface profiling, and direct solid-sample analysis in minutes without dissolution. Integrated optical and mechanical design.",
    specs: [
      ["Detection limit", "Low detection limit"],
      ["Surface analysis", "Layer-by-layer sample surface detection"],
      ["Multi-element", "10+ elements per single measurement"],
      ["Analysis speed", "Sample ready in minutes — very fast detection"],
      ["Sample preparation", "Direct solid analysis — no dilution or dissolution"],
      ["Detection range", "Very wide analytical range"],
      ["Design", "Integrated optical and mechanical whole-machine design"],
      ["Model number", "GD-OES8000"],
      ["Functional mode", "DC or RF"],
      ["Wavelength range", "120–800 nm"],
      ["Spectral resolution", "18 pm – 25 pm"],
      ["Depth resolution", "1–2 nm"],
      ["Sputtering rate", ">1 µm/min"],
      ["Deep profiling scope", "1 nm – 200 µm"],
      ["Focal length", "998.8 mm"],
      ["Element channels", "48"],
      ["Detector", "Photomultiplier tube (PMT)"],
    ],
    image: `${base}uskunalar/GDS8000.png`,
  },
  {
    id: 7,
    name: "AU8000 Precious Metal Analyzer",
    brand: "SOOHOW",
    model: "AU8000",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "XRF analyzer, S–U, 24 elements, GB/T 18043-2013",
    badges: ["BESTSELLER"],
    desc: "AU8000 XRF precious metal analyzer meets GB/T 18043-2013. Si-PIN semiconductor detector delivers accuracy far beyond proportional counters for gold, silver, platinum, palladium, copper, zinc, and nickel in gold, platinum, and K-gold jewelry.",
    specs: [
      ["Standard", "GB/T 18043-2013"],
      ["Detector", "Si-PIN semiconductor — superior to proportional counter"],
      ["Elements analyzed", "Au, Ag, Pt, Pd, Cu, Zn, Ni in jewelry alloys"],
      ["X-ray tube", "Long-life stabilized tube"],
      ["Cooling", "Si-PIN electric refrigeration — no liquid nitrogen"],
      ["Sample camera", "Built-in HD camera — real-time observation"],
      ["Signal processing", "Digital pulse processor; fast, accurate"],
      ["Sample chamber", "Single chamber; manual safety cover"],
      ["Security", "Triple security protection mode"],
      ["Software", "Multivariate regression; matrix correction; friendly UI"],
      ["Configuration", "Si-PIN, multi-channel analysis, X-ray tube, HV/LV, collimator, PC & printer"],
      ["Element range", "S–U (sulfur to uranium)"],
      ["Analytical range", "99.99% purity down to ppm"],
      ["Simultaneous elements", "24 elements"],
      ["Best resolution", "149 eV"],
      ["Detection limit", "ppm level"],
      ["Stability / repeatability", "0.05% (content above 96%)"],
      ["Measure time", "60–200 s (adjustable)"],
      ["Sample types", "Powder, solid, liquid"],
      ["Ambient temperature", "15–30°C"],
      ["Input voltage", "AC 220 V ±5 V (stabilized supply recommended)"],
    ],
    image: `${base}uskunalar/AU8000.png`,
  },
  {
    id: 8,
    name: "OIL8000 RDE-OES Elemental Analyzer",
    brand: "SOOHOW",
    model: "OIL8000",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "RDE-OES oil analysis, <1 ppm, <30 s/test",
    badges: [],
    desc: "OIL8000 rotating disc electrode optical emission spectrometer for rapid elemental analysis of lubricating oils and fluids. Meets ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, and HB 20094.1-2012. No sample pre-treatment or chemical reagents required.",
    specs: [
      ["Test standards", "ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, HB 20094.1-2012"],
      ["Optical design", "Ultra-long focal length for excellent resolution"],
      ["Detection accuracy", "High accuracy; detection limit <1 ppm"],
      ["Test speed", "Single test under 30 seconds"],
      ["Ease of use", "Simple operation and maintenance; low training requirements"],
      ["Sample handling", "No pre-treatment; no chemical reagents; safe and eco-friendly"],
      ["Diffraction grating", "Holographic, 2700 lines/mm"],
      ["Focal length", "500 mm"],
      ["Spectral range", "190–800 nm (by grating selection)"],
      ["Data acquisition", "Microprocessor multi-channel integration; 16-bit ADC"],
      ["Microcontroller", "SP Mixed Signal Flash MCU, 100 MHz; high-speed USB"],
      ["Analysis software", "Create/modify analyzers; print up to 100 results with SD/RSD"],
      ["Power supply", "220 V ±10%, single phase, 50/60 Hz, 10 A, 1.5 kVA"],
      ["Dimensions (L×W×H)", "810 × 500 × 675 mm"],
      ["Weight", "Approx. 52 kg"],
    ],
    image: `${base}uskunalar/OIL8000.png`,
  },
  {
    id: 9,
    name: "OIL8000H RDE-OES Elemental Analyzer",
    brand: "SOOHOW",
    model: "OIL8000H",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "RDE-OES, 32 elements, 30 s/test, 0–6000 ppm",
    badges: ["NEW"],
    desc: "OIL8000H rotating disc electrode optical emission spectrometer for oil and lubricant analysis. Meets ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, and HB 20094.1-2012. Direct oil testing in sample cup — no gas, no chemical reagents, no pretreatment.",
    specs: [
      ["Test standards", "ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, HB 20094.1-2012"],
      ["Constant temperature", "38 °C ± 0.1 °C"],
      ["Test time", "30 seconds per sample"],
      ["Elements analyzed", "32 trace elements simultaneously (24 standard, expandable to 32)"],
      ["Detection accuracy", "Limit 1 ppm; repeatability < ±10%"],
      ["Ease of use", "No assist gas or chemical reagents; oil tested directly in cup"],
      ["Power supply", "AC 220 V ±10%, 50–60 Hz"],
      ["Ambient temperature", "0–55 °C"],
      ["Optical structure", "Paschen-Runge; Roland circle device"],
      ["Focal length", "500 mm"],
      ["Spectral range", "190–800 nm"],
      ["Detector", "CCD"],
      ["Measuring range", "0–6000 ppm"],
      ["Dimensions (L×W×H)", "860 × 410 × 620 mm"],
      ["Weight", "Approx. 97 kg"],
    ],
    image: `${base}uskunalar/OIL8000H.png`,
  },
  {
    id: 10,
    name: "PO100 RDE-OES Elemental Analyzer",
    brand: "SOOHOW",
    model: "PO100",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Portable RDE-OES, <1 ppm, 30 s, 0–6000 ppm",
    badges: [],
    desc: "PO100 compact benchtop RDE-OES for oil analysis with built-in PC and electrode grinder. Patented digital arc source, high-resolution CCD, and Windows analysis software. Ideal for ship environments — no argon or chemical solvents required.",
    specs: [
      ["Test standards", "ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, HB 20094.1-2012"],
      ["Light source", "Patented digital arc; solid-state excitation; constant current"],
      ["Optical system", "High-resolution CCD; 3648 pixels; 8×200 µm pixel size"],
      ["Software", "Windows (7/10+); control, data management, qualitative & quantitative analysis"],
      ["Design", "Benchtop with built-in computer and motor grinder; compact and portable"],
      ["Operating environment", "Short warm-up; high reliability; suitable for ship use"],
      ["Sample handling", "No argon, oxygen, or solvents; oil directly in cup — no pretreatment"],
      ["Connectivity", "Built-in scanner; Bluetooth and RS-485; built-in electrode grinder"],
      ["Power supply", "AC 220 V ±10%, 50–60 Hz"],
      ["Ambient temperature", "0–55 °C"],
      ["Test time", "30 s"],
      ["Optical structure", "Paschen-Runge; Roland circle device"],
      ["Focal length", "500 mm"],
      ["Spectral range", "190–800 nm"],
      ["Detector", "CCD"],
      ["Detection limit", "<1 ppm"],
      ["Elements", "24 standard; expandable to 32"],
      ["Measuring range", "0–6000 ppm"],
      ["Dimensions (L×W×H)", "770 × 360 × 560 mm"],
      ["Weight", "Approx. 53 kg"],
    ],
    image: `${base}uskunalar/PO100.png`,
  },
  {
    id: 11,
    name: "PO200 RDE-OES Elemental Analyzer",
    brand: "SOOHOW",
    model: "PO200",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "RDE-OES, <1 ppm, 30 s, 0–6000 ppm",
    badges: ["BESTSELLER"],
    desc: "PO200 rotating graphite disc electrode optical emission spectrometer for quantitative trace-element analysis in lubricating oils, hydraulic fluids, fuels, greases, and industrial fluids. Used in military, aviation, marine, mining, power, and commercial oil laboratories.",
    specs: [
      ["Principle", "Rotating disc electrode atomic emission spectroscopy (RDE-OES)"],
      ["Subsystems", "Arc excitation supply; disc/rod electrode system; Paschen-Runge optics; CCD measurement; analysis software"],
      ["Applications", "New and used oils, hydraulic oils, gasoline/diesel, heavy oils, greases, antifreeze, industrial water"],
      ["Power supply", "AC 220 V ±10%, 50–60 Hz"],
      ["Ambient temperature", "0–55 °C"],
      ["Test time", "30 s"],
      ["Optical structure", "Paschen-Runge; Rowland circle device"],
      ["Focal length", "500 mm"],
      ["Spectral range", "190–800 nm"],
      ["Detector", "CCD"],
      ["Detection limit", "<1 ppm"],
      ["Elements", "24 standard; expandable to 32"],
      ["Measuring range", "0–6000 ppm"],
      ["Dimensions (L×W×H)", "660 × 360 × 520 mm"],
      ["Weight", "Approx. 64 kg"],
    ],
    image: `${base}uskunalar/PO200.png`,
  },
  {
    id: 12,
    name: "PO300 RDE-OES Elemental Analyzer",
    brand: "SOOHOW",
    model: "PO300",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Compact RDE-OES, 400 mm focus, ≤30 s",
    badges: [],
    desc: "PO300 RDE-OES elemental analyzer uses a graphite rotating disc electrode and atomic emission spectroscopy for oil composition analysis. Compact single-station design with built-in PC, printer, and electrode grinder — ideal for shipboard and field laboratories.",
    specs: [
      ["Principle", "Graphite rotating disc electrode atomic emission spectroscopy"],
      ["Subsystems", "Arc excitation supply; electrode system; Paschen-Runge spectrometer; CCD detection; control & software"],
      ["Applications", "Lubricating oils, hydraulic oils, fuels, greases, antifreeze, industrial water, turbine condensate"],
      ["Industries", "Military, aviation, marine, transport, steel, mining, power plants, oil testing labs"],
      ["Test standards", "ASTM D6595, ASTM D6728, NB/SH/T 0865-2013, HB 20094.1-2012"],
      ["Light source", "Patented digital arc; solid-state excitation; constant current"],
      ["Optical system", "High-resolution CCD; 3648 pixels; 8×200 µm pixel size"],
      ["Software", "Windows 7/10+; instrument control, data management, qualitative & quantitative analysis"],
      ["Design", "Built-in computer, printer, and motor grinder; compact and portable"],
      ["Sample handling", "No argon, oxygen, or solvents; oil directly in cup — no pretreatment"],
      ["Detector", "CCD"],
      ["Focal length", "400 mm"],
      ["Spectral range", "190–800 nm"],
      ["Test time", "≤30 s"],
      ["Dimensions (L×W×H)", "550 × 330 × 430 mm"],
    ],
    image: `${base}uskunalar/PO300.png`,
  },
  {
    id: 13,
    name: "OA8000 XRF Analyser",
    brand: "SOOHOW",
    model: "OA8000",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Portable EDXRF, Mg–U, 2 ppm–99.99%, 30–300 s",
    badges: ["NEW"],
    desc: "OA8000 portable XRF analyser for railways, subways, ships, and on-site laboratories. Qualitative and quantitative analysis of wear metals, additive consumption, and contaminants in lubricating oils, greases, and transmission fluids. Simple enough for non-specialists, with results in minutes wherever oil is used. Also suited to sulfur, heavy metals, additives, and contaminants in gasoline, diesel, jet fuel, kerosene, hydraulic oils, crude and residual oil, wax oil, alcohol gasoline, biodiesel, and related petroleum products.",
    specs: [
      ["Applications", "Railways, subways, ships — wear metals and oil condition monitoring"],
      ["Analysis type", "Qualitative and quantitative elemental analysis"],
      ["Sample types", "Lubricating oils, greases, fuels, hydraulic fluids, petroleum products"],
      ["Analysis element range", "Mg–U (magnesium to uranium)"],
      ["Test subject", "Solids, powders, liquids"],
      ["Content range", "2 ppm – 99.99%"],
      ["Analysis method", "Energy dispersive X-ray fluorescence (EDXRF)"],
      ["Detector", "SDD / Fast SDD detector"],
      ["Operating temperature", "-10°C to +50°C"],
      ["Operating humidity", "<90%"],
      ["Detection limit (S in fuel)", "10 ppm (typical)"],
      ["Controllability", "One-click test"],
      ["Detection time", "30–300 s"],
    ],
    image: `${base}uskunalar/IOA8000.png`,
  },
  {
    id: 14,
    name: "PQ100 Ferrous Debris Monitor",
    brand: "SOOHOW",
    model: "PQ100",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Ferrous debris monitor, ASTM D8184, 7 s, 0–15000 PQ",
    badges: ["NEW"],
    desc: "PQ100 ferrous debris monitor for ferromagnetic wear particles in lubricating oils, meeting ASTM D8184. Patented sensor and signal processing circuit provide high stability and sensitivity. Automatic oil transfer and measurement in 7 seconds—samples need no pretreatment and can be measured directly in the bottle. PC software imports data for management, trend analysis, and curve printing. Graphical interface for easy operation; alphanumeric naming for saved files.",
    specs: [
      ["Test standard", "ASTM D8184"],
      ["Sensor", "Patented sensor and signal processing — high stability and sensitivity"],
      ["Measurement", "Automatic sample transfer; 7 s per reading"],
      ["Sample handling", "No pretreatment; direct injection into oil bottle"],
      ["PC software", "Data import, trend analysis, curve printing"],
      ["User interface", "Graphical interface; alphanumeric file naming"],
      ["Power supply", "AC 220 V ±10%, 50–60 Hz"],
      ["Ambient temperature", "0°C to 30°C"],
      ["Display", "LCD 120×90"],
      ["Repeatability", "±4 PQ or ±1% (whichever is greater)"],
      ["Resolution", "1 PQ"],
      ["Measurable minimum", "5 PQ"],
      ["Abrasive detection", ">1 µm ferromagnetic abrasive particles"],
      ["Connection", "USB port"],
      ["Measuring range", "0–15000 PQ"],
      ["Dimensions (L×W×H)", "370 × 222 × 140 mm"],
      ["Weight", "3.8 kg"],
    ],
    image: `${base}uskunalar/PQ100.png`,
  },
  {
    id: 15,
    name: "PQ200-PQL Ferrous Debris Monitor",
    brand: "SOOHOW",
    model: "PQ200-PQL",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Ferrous debris monitor, 7 s, 0–15000 PQ, 4.2 kg",
    badges: ["NEW"],
    desc: "PQ200-PQL ferrous debris monitor for ferromagnetic wear particles in lubricating oils. Patented sensor and signal processing circuit deliver high stability and sensitivity. Automatic oil transfer and measurement in 7 seconds—samples need no pretreatment and can be measured directly in the bottle. PC software imports data for management, trend analysis, and curve printing. Graphical interface for easy operation; alphanumeric naming for saved files.",
    specs: [
      ["Sensor", "Patented sensor and signal processing — high stability and sensitivity"],
      ["Measurement", "Automatic sample transfer; 7 s per reading"],
      ["Sample handling", "No pretreatment; direct injection into oil bottle"],
      ["PC software", "Data import, trend analysis, curve printing"],
      ["User interface", "Graphical interface; alphanumeric file naming"],
      ["Power supply", "AC 220 V ±10%, 50–60 Hz"],
      ["Ambient temperature", "10°C to 30°C"],
      ["Display", "LCD 120×90"],
      ["Repeatability", "±4 PQ or ±1% (whichever is greater)"],
      ["Resolution", "1 PQ"],
      ["Measurable minimum", "5 PQ"],
      ["Abrasive detection", ">1 µm ferromagnetic abrasive particles"],
      ["Connection", "USB port"],
      ["Measuring range", "0–15000 PQ"],
      ["Dimensions (L×W×H)", "370 × 220 × 136 mm"],
      ["Weight", "4.2 kg"],
    ],
    image: `${base}uskunalar/PQ200.png`,
  },
  {
    id: 16,
    name: "PQ300(B)-PQL Ferrous Debris Monitor",
    brand: "SOOHOW",
    model: "PQ300(B)-PQL",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Ferrous debris monitor, 7 s, 7\" display, PQ300 / PQ300B",
    badges: ["NEW"],
    desc: "PQ300(B)-PQL ferrous debris monitor for ferromagnetic wear particles in lubricating oils. Patented sensor and signal processing deliver high stability and sensitivity. Automatic measurement in 7 seconds with direct injection into the sample bottle—no pretreatment. PC software supports data import, trend analysis, and curve printing. Bilingual (Chinese/English) graphical interface with alphanumeric file naming. PQ300: AC 220 V to 24 V adapter; PQ300B: 3 A charger with built-in 3200 mAh rechargeable lithium battery.",
    specs: [
      ["Sensor", "Patented sensor and signal processing — high stability and sensitivity"],
      ["Measurement", "Automatic sample transfer; 7 s per reading"],
      ["Sample handling", "No pretreatment; direct injection into oil bottle"],
      ["PC software", "Data import, trend analysis, curve printing"],
      ["User interface", "Chinese/English graphical UI; alphanumeric file naming"],
      ["Power — PQ300", "AC 220 V to 24 V adapter"],
      ["Power — PQ300B", "3 A charger + built-in 3200 mAh Li-ion battery"],
      ["Ambient temperature", "10°C to 30°C"],
      ["Display", "7-inch screen"],
      ["Repeatability", "±4 PQ or ±1% (whichever is greater)"],
      ["Resolution", "1 PQ"],
      ["Measurable minimum", "5 PQ"],
      ["Abrasive detection", ">1 µm ferromagnetic abrasive particles"],
      ["Connection", "USB port"],
      ["Measuring range", "0–15000 PQ"],
      ["Dimensions (L×W×H)", "430 × 225 × 140 mm"],
      ["Weight", "4.7 kg (PQ300) / 5.1 kg (PQ300B)"],
    ],
    image: `${base}uskunalar/PQ300%28B%29.jpg`,
  },
  {
    id: 17,
    name: "PA100 Ferrogram Maker",
    brand: "SOOHOW",
    model: "PA100",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Ferrogram maker, ASTM D7690, 2 slides <20 min, ~1.5 T",
    badges: ["NEW"],
    desc: "PA100 ferrogram maker prepares transparent ferrographic slides from lubricating oil for wear particle analysis, meeting ASTM D7690 and SH/T 0573. Moisture in the oil has little effect on slide quality. After the sample is loaded, operation is automated so the operator can perform other tasks. Two ferrograms are produced simultaneously in under 20 minutes. Transparent deposits distinguish metallic, organic, and non-metallic particles; particles align by magnetic susceptibility and size for rapid machine-condition interpretation.",
    specs: [
      ["Test standards", "ASTM D7690; SH/T 0573"],
      ["Throughput", "2 ferrograms automatic or semi-automatic simultaneously; <20 min"],
      ["Moisture sensitivity", "Oil moisture has little effect on preparation"],
      ["Operation", "Easy push-button control; adjustable flow for repeatability"],
      ["Deposition", "Transparent spectrum; particles sorted by susceptibility and size"],
      ["Particle observation", "Low particle accumulation — critical wear particles easy to view"],
      ["Magnetic field", "Max. flux density ~1.5 T"],
      ["Magnetic gradient", ">0.5 T/mm"],
      ["Oil flow rate", "10–30 ml/h"],
      ["Delivery tube", "OD 2.6 mm; ID 1.8 mm"],
      ["Ferrograph inclination", "1–5°"],
      ["Substrate size", "60 × 24 × 0.17 mm (L×W×H)"],
      ["Microscope — optics", "Infinity-corrected system; EW10×/22 eyepiece"],
      ["Microscope — objectives", "5×, 10×, 20×, 50×, 100× infinity plan achromat"],
      ["Microscope — head", "Hinged trinocular, 30° tilt, interpupillary 48–75 mm"],
      ["Microscope — illumination", "24 V / 100 W halogen; Köhler; BF/DF"],
      ["Microscope — focusing", "Coaxial coarse/fine; 1 µm fine division"],
      ["Microscope — converter", "Five-position nosepiece"],
      ["Max. specimen height", "50 mm"],
    ],
    image: `${base}uskunalar/PA100.png`,
  },
  {
    id: 18,
    name: "PA200 Ferrogram Maker",
    brand: "SOOHOW",
    model: "PA200",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Dual-channel ferrogram, 0–800 µm, 14 kg, ASTM D7690",
    badges: ["NEW"],
    desc: "PA200 ferrogram maker prepares transparent ferrographic slides for wear particle analysis per ASTM D7690, ASTM D7684, and SH/T 0573. Oil water content has little effect on preparation. After loading, the instrument runs automatically while the operator performs other tasks. Dual-channel synchronous operation produces two ferrograms in under 20 minutes with adjustable flow for repeatable deposition. Transparent slides distinguish metallic, organic, and non-metallic particles arranged by magnetization and size. Permanent-magnet high-gradient field reduces accumulation; tetrachloroethylene used as dilution and cleaning solvent.",
    specs: [
      ["Test standards", "ASTM D7690; ASTM D7684; SH/T 0573"],
      ["Throughput", "Dual-channel synchronous; 2 ferrograms <20 min"],
      ["Wear particle range", "0–800 µm"],
      ["Water sensitivity", "Oil water content has little effect on preparation"],
      ["Injection", "Micro-pump pressure; automatic sampling"],
      ["Cleaning", "Automatic and manual cleaning"],
      ["Magnetic field", "Max. 1.5 T (±0.1 T); gradient >0.5 T/mm — permanent magnet"],
      ["Solvent", "Tetrachloroethylene dilution and cleaning"],
      ["Plate inclination", "1–5°"],
      ["Display", "Two 1.54\" OLED — real-time status"],
      ["Oil transfer speed", "10–30 ml/h"],
      ["Cleaning agent flow", "10–30 ml/h"],
      ["Resolution", "1 µm"],
      ["Sample per analysis", "1 ml"],
      ["Delivery tube", "OD 2.6 mm; ID 1.8 mm"],
      ["Substrate size", "60 × 24 × 0.17 mm"],
      ["Accessories", "Standard abrasive particle atlas; ferrographic slides and consumables"],
      ["Waste handling", "Built-in waste collection; vacuum pump to waste bottle"],
      ["Power supply", "AC 220 V, 50 Hz"],
      ["Dimensions (L×W×H)", "395 × 355 × 335 mm"],
      ["Weight", "Approx. 14 kg"],
    ],
    image: `${base}uskunalar/PA200.png`,
  },
  {
    id: 19,
    name: "PA300 Ferrogram Maker",
    brand: "SOOHOW",
    model: "PA300",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Dual-channel ferrogram, 10.1\" touch LCD, 0–800 µm",
    badges: ["NEW"],
    desc: "PA300 ferrogram maker prepares transparent ferrographic slides for wear particle analysis per ASTM D7690, ASTM D7684, and SH/T 0573. Oil water content has little effect on preparation. After loading, operation is fully automatic. Dual-channel synchronous spectroscopy produces two ferrograms in under 20 minutes with adjustable oil flow (10–30 ml/h) for repeatable deposition. Transparent slides distinguish metallic, organic, and non-metallic particles sorted by magnetization and size. Features a 10.1-inch LCD touchscreen, 12 V power adapter, and built-in waste liquid collection with vacuum pump.",
    specs: [
      ["Test standards", "ASTM D7690; ASTM D7684; SH/T 0573"],
      ["Throughput", "Dual-channel synchronous; 2 ferrograms <20 min"],
      ["Wear particle range", "0–800 µm"],
      ["Water sensitivity", "Oil water content has little effect on preparation"],
      ["Injection", "Micro-pump pressure; automatic sampling"],
      ["Cleaning", "Automatic and manual cleaning"],
      ["Magnetic field", "Max. 1.5 T (±0.1 T); gradient >0.5 T/mm — permanent magnet"],
      ["Solvent", "Tetrachloroethylene dilution and cleaning"],
      ["Plate inclination", "1–5°"],
      ["Display", "10.1-inch LCD touchscreen"],
      ["Oil transfer speed", "10–30 ml/h adjustable"],
      ["Cleaning agent flow", "Adjustable; max. >100 ml/h"],
      ["Resolution", "1 µm"],
      ["Sample per analysis", "1 ml"],
      ["Delivery tube", "OD 2.6 mm; ID 1.8 mm"],
      ["Substrate size", "60 × 24 × 0.17 mm"],
      ["Accessories", "Standard abrasive particle atlas; ferrographic slides and consumables"],
      ["Waste handling", "Built-in waste collection; vacuum pump to waste bottle"],
      ["Power supply", "AC 220 V, 50 Hz; includes 12 V power adapter"],
      ["Dimensions (L×W×H)", "395 × 355 × 335 mm"],
      ["Weight", "Approx. 14 kg"],
    ],
    image: `${base}uskunalar/PA300.png`,
  },
  {
    id: 20,
    name: "PJ500 Laboratory Ferrography",
    brand: "SOOHOW",
    model: "PJ500",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Lab ferrography, 0–800 µm, 1.5 T, portable 9.6 kg",
    badges: ["NEW"],
    desc: "PJ500 laboratory ferrography separates wear and contaminant particles from oil without deformation, meeting ASTM D7690, ASTM D7684, and SH/T 0573-1993. High-gradient permanent magnet arranges ferromagnetic particles orderly for microscopy. Reference ferrogram library aids fault location and root-cause analysis. Minimal solvent use, no compressed air required; volatile cleaning agents are contained for operator safety. One-click rotating thimble design for quick maintenance. Portable for field use with adjustable ferrography speed and positioning for reproducible deposition.",
    specs: [
      ["Test standards", "ASTM D7690; ASTM D7684; SH/T 0573-1993"],
      ["Particle inspection range", "0–800 µm"],
      ["Sample introduction", "Manual — thimble capillary; gravity drip"],
      ["Injection flow rate", "0.4 ml/min"],
      ["Oil sample volume", "2–3 ml per analysis"],
      ["Magnetic field", "Max. 1.5 T; gradient >0.5 T/cm"],
      ["Magnet design", "Optimized permanent magnet; high-gradient orderly particle arrangement"],
      ["Cleaning", "Automatic; schedulable; adjustable speed"],
      ["Ferrogram size", "60 × 24 × 0.17 mm"],
      ["Display", "3.5\" TFT"],
      ["Analysis content", "Concentration, size, morphology, composition of wear particles"],
      ["Reference library", "Ferrogram atlas for fault location and cause"],
      ["Operation", "Low solvent; no external compressed air"],
      ["Safety", "Volatile solvents contained — protects personnel"],
      ["Maintenance", "One-click rotating thimble for quick glass replacement"],
      ["Positioning", "Adjustable tube-to-substrate distance for reproducibility"],
      ["Operating temperature", "18–35°C"],
      ["Power supply", "AC 220 V ±10%, 50 Hz"],
      ["Dimensions (L×W×H)", "340 × 300 × 430 mm"],
      ["Weight", "9.6 kg"],
    ],
    image: `${base}uskunalar/PJ500.jpg`,
  },
  {
    id: 21,
    name: "RF500 Rotary Particle Depositor",
    brand: "SOOHOW",
    model: "RF500",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Rotary depositor, dual-channel, 0–3000 µm, 16 MP imaging",
    badges: ["NEW"],
    desc: "RF500 rotary particle depositor prepares ferrographic spectra with dual-channel synchronous operation and independent channels. Physical buttons plus 10.1-inch LCD touchscreen; automatic spectrum mounting and fixing. Dual-head strong magnetic design with three concentric rings deposits large-, medium-, and small abrasive grains efficiently. Adjustable head speed and cycle time suit different oil viscosities. Active pump-driven waste recovery, power-loss memory, and timed production, cleaning, and drying. Includes high-resolution dual optical-path microscope, 16-megapixel imaging, and desktop computer.",
    specs: [
      ["Interface", "Physical buttons + 10.1\" LCD touchscreen"],
      ["Channels", "Dual-channel synchronous; independent operation"],
      ["Spectrum handling", "Automatic install and fix device"],
      ["Drive", "Dual-channel stepper; vertical motors; no cross-interference"],
      ["Timing", "Timekeeping per status; adjustable production/clean/dry cycles"],
      ["Magnetic head", "Dual-head; three concentric rings (large/medium/small grains)"],
      ["Head speed (default)", "Production 75 rpm; cleaning 150 rpm; drying 200 rpm (adjustable)"],
      ["Magnetic gradient", "100–1000 Gs in deposition area; ≥600 Gs at working point"],
      ["Measurement range", "0–3000 µm"],
      ["Head runout", "Radial and end-face <±100 µm"],
      ["Substrate size", "55 × 55 × 0.17 mm"],
      ["Deposition area", "Equal-odds outer ring ≥47 mm²; inner ring ≥9 mm²"],
      ["Reproducibility", "Qualitative iron spectra <10% (8 FOV); quantitative <15% (4 FOV)"],
      ["Cleaning", "Automatic injection; adjustable speed and duration"],
      ["Waste recovery", "Active pump-driven — reduces blockage, improves efficiency"],
      ["Power protection", "Outage memory — resumes spectrum production after power return"],
      ["Imaging", "Dual optical-path microscope; 16 MP camera; desktop PC included"],
      ["Power supply", "220 V ±10% AC, 50 Hz; 24 V 6 A adapter"],
      ["Power consumption", "<150 W"],
      ["Dimensions (L×W×H)", "700 × 280 × 240 mm"],
      ["Weight", "Approx. 14 kg"],
    ],
    image: `${base}uskunalar/RF500.png`,
  },
  {
    id: 22,
    name: "DR100 Direct Reading Ferrograph",
    brand: "SOOHOW",
    model: "DR100",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Direct-reading ferrograph, <10 min, 7\" touch, 1 ml",
    badges: ["NEW"],
    desc: "DR100 direct-reading ferrograph quickly measures and quantifies all ferromagnetic wear particles in lubricating oil, hydraulic fluid, coolant, or fuel. Seven-inch sensitive touchscreen with Windows 7, USB (4 ports), and RJ45 networking. Microprocessor self-diagnosis ensures reliable operation. Trend analysis detects early wear intensity changes to prevent serious equipment losses. Portable for field use with positioning device for consistent sample entry. Results in minutes for wear particle concentration and basic wear trends.",
    specs: [
      ["Sample volume", "1 ml per sampling"],
      ["Analysis time", "<10 minutes per test"],
      ["Display", "7-inch high-sensitivity touchscreen"],
      ["Operating system", "Windows 7"],
      ["Connectivity", "4× USB; RJ45 Ethernet"],
      ["Injection", "Automatic injection"],
      ["Cleaning agent", "Tetrachloroethylene"],
      ["Magnetic field", "Max. gradient >5.0 T/cm; max. flux density >1.5 T"],
      ["Test resolution", "0.1 (one decimal place)"],
      ["Self-diagnosis", "Internal microprocessor self-diagnosis"],
      ["Trend analysis", "Early wear detection; adjustable sampling frequency"],
      ["Positioning", "Adjustable pipeline-to-sensor distance for accuracy"],
      ["Applications", "Lubricating oil, hydraulic oil, coolant, fuel"],
      ["Output", "Quantitative wear concentration and wear trend data"],
      ["Power supply", "220 V AC ±10%, 50 Hz; 12 V DC 5 A adapter"],
    ],
    image: `${base}uskunalar/DR100.png`,
  },
  {
    id: 23,
    name: "IFP100 Portable Intelligent Ferrograph Analyzer",
    brand: "SOOHOW",
    model: "IFP100",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Portable ferrograph, 5–500 µm, <1 min, 12.1\" touch",
    badges: ["NEW"],
    desc: "IFP100 portable intelligent ferrograph analyzer uses electromagnetic adsorption and image recognition to analyze ferromagnetic wear particles in lubricating oil in under one minute. Sixfold optical magnification with 5 MP CMOS camera captures particle surface texture and color. Stepless magnetic field (256 levels) classifies particles as normal abrasive, adhesive, sliding, or cutting wear. Automatic injection and cleaning with software monitoring. Auto-generated reports with wear evaluation and maintenance advice. Compact PP shell with precision aluminum control panel for field use.",
    specs: [
      ["Detection principle", "Electromagnetic adsorption + image recognition"],
      ["Detection range", "5–500 µm"],
      ["Detection time", "<1 minute"],
      ["Light source", "LED reflective"],
      ["Optical magnification", "6×"],
      ["Camera", "5 MP CMOS; 2592 × 1944 resolution"],
      ["Magnetic field", "Built-in; stepless 256 levels"],
      ["Wear types", "Normal abrasive; adhesive; sliding; cutting"],
      ["Output indicators", "Total wear; large/small particle counts; equivalent radius; major axis; wear evaluation"],
      ["Software", "Sample/device management; history reports; trend statistics"],
      ["Automation", "Auto injection and cleaning; adjustable sampling/cleaning duration"],
      ["Reporting", "Auto detection reports; wear evaluation and maintenance advice"],
      ["Display", "12.1\" 1280×800 color LCD touchscreen"],
      ["Processor", "8-core 64-bit (4×A76 @2.4 GHz + 4×A55 @1.8 GHz)"],
      ["NPU", "Up to 6 TOPS (INT4/8/16, FP16)"],
      ["Memory / storage", "16 GB RAM; 256 GB eMMC"],
      ["Interface tube", "Nylon OD 6 mm; ID 4 mm"],
      ["Operating temperature", "-20°C to 60°C"],
      ["Power", "DC 24 V or adapter; <100 W"],
      ["Output ports", "USB / RJ45"],
      ["Enclosure", "PP shell; precision aluminum control panel"],
      ["Weight", "10 ±0.2 kg"],
    ],
    image: `${base}uskunalar/IFP100.png`,
  },
  {
    id: 24,
    name: "PF100 Ferrous Wear Meter",
    brand: "SOOHOW",
    model: "PF100",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Ferrous wear meter, ASTM D8120, 0–2500 ppm, <3 s",
    badges: ["NEW"],
    desc: "PF100 ferrous wear meter quantifies ferrous debris in oil per ASTM D8120 using precision magnetometry. Ideal for cylinder friction oil, gearbox lubricants, bearing oils, and on-site ship or remote monitoring where full laboratory analysis is unavailable. Simple platform with high accuracy and reliability. Applications include machine wear monitoring, lubricant evaluation, gearbox ferrous debris assessment, and bearing oil analysis.",
    specs: [
      ["Test standard", "ASTM D8120 — ferrous debris quantification"],
      ["Measurement range", "0–2500 ppm"],
      ["Measurement method", "Ferromagnetic method"],
      ["Display resolution", "5 ppm"],
      ["Repeatability", "±10 ppm (0–1000 ppm); ±20 ppm (>1001 ppm)"],
      ["Sample vial", "Standard 5 ml test tube"],
      ["Test time", "<3 seconds per sample"],
      ["Operating temperature", "5°C to 40°C"],
      ["Power supply", "24 V DC; UK, EU, and US adapters included"],
      ["Weight", "1.1 kg"],
      ["Applications", "Machine wear; lubricant evaluation; gearbox; bearing oil"],
    ],
    image: `${base}uskunalar/PF100.jpg`,
  },
  {
    id: 25,
    name: "SLPC 100 Particle Counting System",
    brand: "SOOHOW",
    model: "SLPC 100",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Particle counter, ISO 4402, 32 ch., 0.8–500 µm",
    badges: ["NEW"],
    desc: "SLPC 100 particle counting system uses the light-blocking method with a high-performance large-size particle count sensor. Calibration, detection, and accuracy meet ISO 4402, GB/T 18854, and ISO 11171. Built-in cleanliness codes include NAS 1638, ISO 4406 (multiple revisions), GB/T 14039, GJB 420, AS4059, and more. Industrial PC with Windows controls the instrument; results via built-in printer, software database, or USB. Optional calibration curves: ACFTD, ISOMTD, latex ball, GOST, and others.",
    specs: [
      ["Principle", "Light-blocking method"],
      ["Standards", "ISO 4402; GB/T 18854; ISO 11171"],
      ["Cleanliness codes", "NAS 1638, ISO 4406, GB/T 14039, GJB 420, AS4059, and more (expandable)"],
      ["Light source", "Semiconductor laser"],
      ["Detection range", "0.8–500 µm"],
      ["Particle size range", "1–100 µm (ISO 4402) or 4–70 µm(c) (GB/T 18854, ISO 11171)"],
      ["Sensitivity", "1 µm (ISO 4402) or 4 µm(c) (GB/T 18854, ISO 11171)"],
      ["Detection channels", "32; size settable at 0.01 µm intervals"],
      ["Sample volume", "0.3–100 ml (0.1 ml steps)"],
      ["Sampling volume error", "Better than ±0.5%"],
      ["Detection / cleaning speed", "5–60 mL/min (default 15 mL/min)"],
      ["Resolution", "Better than 10%"],
      ["Coincidence error limit", "12,000–40,000 particles/mL"],
      ["Repeatability", "RSD <2%"],
      ["Detection accuracy", "±4%, 1/2 rating (ISO 4406)"],
      ["Particle count error", "±5%"],
      ["Sample pressure", "Max. +0.8 MPa; max. vacuum −0.08 MPa"],
      ["Sample viscosity", "<650 cSt"],
      ["Sample temperature", "0–80°C"],
      ["Working / storage temp.", "Working −20–60°C; storage −30–80°C"],
      ["Control", "Industrial PC; Windows"],
      ["Data storage", "Built-in printer; software database; USB"],
      ["Calibration curves", "Optional ACFTD, ISOMTD, latex ball, GOST, etc."],
      ["Power supply", "220 V ±10%, 50 Hz; 180 W"],
      ["Dimensions (L×W×H)", "355 × 400 × 620 mm"],
      ["Weight", "19 kg"],
    ],
    image: `${base}uskunalar/SLPC%20100.png`,
  },
  {
    id: 26,
    name: "SLPC300 Portable Particle Counter",
    brand: "SOOHOW",
    model: "SLPC300",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Portable particle counter, 8+8 ch., 0.8–600 µm, battery",
    badges: ["NEW"],
    desc: "SLPC300 portable particle counter offers 1000 particle size channels with built-in data analysis for automatic sample grading, processing, and printing. Color touchscreen in Chinese and English with preset and stored methods. RS232 and USB connectivity; built-in 5200 mAh lithium battery for 6–8 hours of field operation without mains power. Rugged embedded design for construction machinery, military, aerospace, power, and marine environments.",
    specs: [
      ["Analysis channels", "1000 particle size channels"],
      ["Data system", "Built-in analysis; auto grade; print function"],
      ["Interface", "Color touchscreen; Chinese/English; preset and storage"],
      ["Connectivity", "RS232; USB data storage"],
      ["Battery", "5200 mAh Li-ion; 6–8 h runtime"],
      ["Light source", "Semiconductor laser"],
      ["Particle size range", "0.8–600 µm (calibrated 1–100 µm or 4–70 µm(c))"],
      ["Sensitivity", "0.1 µm"],
      ["Detection channels", "8+8 channels; arbitrary particle size settings"],
      ["Sample volume", "0.2–1000 ml (0.1 ml steps)"],
      ["Sampling accuracy", "Better than ±1%"],
      ["Sampling / cleaning speed", "5–80 mL/min"],
      ["Counting accuracy", "<±5%"],
      ["Resolution", "≤10%"],
      ["Repeatability", "RSD <2%"],
      ["Coincidence error limit", "1,200–40,000 particles/mL"],
      ["Offline viscosity", "≤100 cSt (optional pneumatic chamber for high viscosity)"],
      ["Pressure range", "Low 0–0.6 MPa; high up to 30 MPa (optional reducer)"],
      ["Online interval", "Arbitrary settings"],
      ["Sample temperature", "0–80°C"],
      ["Working / storage temp.", "Working −20–60°C; storage −30–80°C"],
      ["Power supply", "AC 100–240 V, 50/60 Hz"],
      ["Dimensions (L×W×H)", "380 × 310 × 205 mm"],
      ["Weight", "8.6 kg"],
      ["Optional", "SLPC300W oil water content measurement module"],
    ],
    image: `${base}uskunalar/SLPC300.png`,
  },
  {
    id: 27,
    name: "OL-1 Online Particle Counter",
    brand: "SOOHOW",
    model: "OL-1",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Online particle counter, 8 ch., 1–600 µm, RS485/232",
    badges: ["NEW"],
    desc: "OL-1 online particle counter provides continuous automatic in-line particle counting with real-time levels and customizable detection intervals. Built-in cleanliness standards include NAS 1638, ISO 4406, GJB 420, ROCT 17216, GB/T 14039, and more. Calibration per ISO 4402, GB/T 18854, and ISO 11171. RS485, RS232, or 4–20 mA output to external systems; real-time flow monitoring. Optional water-activity sensor for micro-water in oil. High-strength aluminum housing for harsh industrial, military, aerospace, and marine environments.",
    specs: [
      ["Cleanliness standards", "NAS 1638, ISO 4406, GJB 420, ROCT 17216, GB/T 14039 (expandable)"],
      ["Calibration", "Built-in per ISO 4402, GB/T 18854, ISO 11171"],
      ["Connectivity", "RS485, RS232, or 4–20 mA to external PC/system"],
      ["Operation", "Continuous online detection; adjustable intervals"],
      ["Flow monitoring", "Real-time sensor flow rate"],
      ["Optional sensor", "Water activity — micro-water in oil"],
      ["Enclosure", "High-strength aluminum; high temp and pressure resistant"],
      ["Light source", "Semiconductor laser"],
      ["Particle size range", "1–600 µm (sensor dependent)"],
      ["Sensitivity", "1 µm (ISO 4402) or 4 µm(c) (GB/T 18854, ISO 11171)"],
      ["Counting volume", "10 ml"],
      ["Counting accuracy", "±1 cleanliness level"],
      ["Test channels", "8 fixed size channels"],
      ["Channel sizes (ISO 4402)", "1, 2, 5, 10, 15, 25, 50, 100 µm"],
      ["Channel sizes (ISO 11171)", "4, 4.6, 6, 10, 14, 21, 38, 70 µm(c)"],
      ["Flow rate range", "10–50 mL/min or 50–300 mL/min"],
      ["Online pressure", "0.2–10 MPa (optional reducer to 40 MPa)"],
      ["Result storage", "USB export to flash drive"],
      ["Sample temperature", "0–80°C"],
      ["Working / storage temp.", "Working −20–60°C; storage −30–80°C"],
      ["Power supply", "DC 9 V or DC 12–36 V"],
      ["Applications", "Military, aerospace, power generation, transportation"],
    ],
    image: `${base}uskunalar/OL-1.png`,
  },
  {
    id: 28,
    name: "PDA100 Portable Automatic Wear Particle Analyzer",
    brand: "SOOHOW",
    model: "PDA100",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Wear particle analyzer, 4–200 µm, <1 min, 12.1\" touch",
    badges: ["NEW"],
    desc: "PDA100 portable automatic wear particle analyzer uses microfluidic imaging recognition to detect contaminants in lubricating oil without bubble interference. Fivefold optical magnification with a 1.3 MP CMOS camera analyzes iron, copper, fibers, bubbles, water droplets, and sludge by color and contour. Outputs contamination levels, wear types, and counts per unit volume. User-defined counting and grading per NAS 1638, ISO 4406, and GJB 420. Automatic sampling and cleaning with 0.1 µL metering pump accuracy; auto-calibration with reference materials.",
    specs: [
      ["Detection principle", "Microfluidic imaging recognition (bubble-resistant)"],
      ["Optical magnification", "5×"],
      ["Detection range", "4–200 µm"],
      ["Camera", "1.3 MP CMOS; 1280 × 1024"],
      ["Test subjects", "Iron, copper, fibers, bubbles, water, sludge, and other contaminants"],
      ["Contamination index", "NAS 1638, ISO 4406, GJB 420; user-defined methods"],
      ["Output", "Contamination level, wear type, quantity per unit volume"],
      ["Software", "Sample/equipment management; history; wear and trend analysis"],
      ["Automation", "Auto intake and cleaning; configurable duration; cleaning monitor"],
      ["Metering pump", "Built-in high-precision pump; ±0.1 µL accuracy"],
      ["Calibration", "Auto with reference materials; third-party metrology supported"],
      ["Display", "12.1\" 1280×800 color LCD touchscreen"],
      ["Processor", "8-core 64-bit (4×A76 @2.4 GHz + 4×A55 @1.8 GHz)"],
      ["NPU", "Up to 6 TOPS (INT4/8/16, FP16)"],
      ["Memory / storage", "16 GB RAM; 256 GB eMMC"],
      ["Interface tube", "Nylon Φ3 mm OD; Φ2 mm ID"],
      ["Detection time", "<1 minute"],
      ["Operating temperature", "-20°C to 60°C"],
      ["Power", "DC 24 V or adapter; <100 W"],
      ["Output ports", "USB / RJ45"],
      ["Enclosure", "PP shell; precision aluminum panel"],
      ["Weight", "10 ±0.2 kg"],
    ],
    image: `${base}uskunalar/PDA100.png`,
  },
  {
    id: 29,
    name: "TBN-200 Portable Total Alkalinity Tester",
    brand: "SOOHOW",
    model: "TBN-200",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Portable TBN & moisture tester, 0–80 TBN, USB, battery",
    badges: ["NEW"],
    desc: "TBN-200 portable total alkalinity tester accurately measures water content and base number (BN/TBN) in lubricating oil for rapid on-site condition monitoring. Compact, rugged housing with a simple four-key panel and immediate results without complex training. USB export for data management; rechargeable 18650 battery for safe field use without mains power. Available configurations for moisture only, BN only, or combined detection. Widely used in automotive, industrial machinery, power generation, mining, shipping, and laboratory quality control.",
    specs: [
      ["Total alkalinity (TBN)", "0–80 TBN; resolution 1 BN; repeatability ≤5 or 10%"],
      ["Moisture content", "0.03–10.0 (V%); repeatability ≤5"],
      ["Pressure sensor", "0–5 bar"],
      ["Pressure chamber", "Threaded rotating bottom cover"],
      ["Interface", "USB (data storage and export)"],
      ["Panel keys", "4 keys: plus, minus, confirm, return"],
      ["Software", "Embedded software"],
      ["Data storage", "Built-in memory; up to 150 result groups"],
      ["Battery", "3.7 V; 18650; 6000 mAh; rechargeable; charging indicator"],
      ["Dimensions", "Ø86 × 88 mm (outer diameter × height)"],
      ["Weight", "0.9 kg"],
      ["Applications", "Automotive, industrial, power, mining, shipping, laboratory QC"],
    ],
    image: `${base}uskunalar/TBN-200.png`,
  },
  {
    id: 30,
    name: "PC550 On-line Particle Counter (High-End Type)",
    brand: "SOOHOW",
    model: "PC550",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Online/offline particle counter, 32 ch., 7\" Android, RS485/232",
    badges: ["NEW"],
    desc: "PC550 on-line particle counter (high-end type) uses the light blockage (light extinction) principle for real-time particle contamination monitoring in hydraulic and lubrication systems — continuous on-site online detection or offline sampling. Adjustable monitoring intervals from 1 second to 24 hours. Calibration, detection methods, and accuracy meet ISO 4402, GB/T 18854, and ISO 11171. Built-in cleanliness rating standards include NAS 1638, ISO 4406 (multiple revisions), GB/T 14039, GJB 420, AS4059, ROCT, JTS, SAE, and custom expandable codes. High-performance large-size particle counting sensor with 32 adjustable channels at 0.1 µm steps. 7-inch industrial Android display for control and analysis. Optional water content sensor; RS485 or RS232 for external data transfer. Results via built-in printer, software database, or USB. Optional calibration curves: ACFTD, ISOMTD, latex spheres, GOST, and others.",
    specs: [
      ["Principle", "Light blockage (light extinction)"],
      ["Detection mode", "Online or offline"],
      ["Standards", "ISO 4402; GB/T 18854; ISO 11171"],
      ["Cleanliness codes", "NAS 1638, ISO 4406, GB/T 14039, GJB 420, AS4059, ROCT, JTS, SAE (expandable)"],
      ["Display / control", "7\" industrial computer; Android OS"],
      ["Connectivity", "RS485 or RS232"],
      ["Optional sensor", "Water content sensor"],
      ["Data storage", "Built-in printer; software database; USB"],
      ["Calibration curves", "Optional ACFTD, ISOMTD, latex spheres, GOST, etc."],
      ["Light source", "Semiconductor laser"],
      ["Online monitoring interval", "1 s to 24 h"],
      ["Online detection pressure", "0.1–0.6 MPa (up to 40 MPa with optional reducer)"],
      ["Sample temperature", "0–80°C"],
      ["Particle size range", "1–500 µm"],
      ["Sensitivity", "1 µm (ISO 4402) or 4 µm(c) (GB/T 18854, ISO 11171)"],
      ["Detection channels", "32 channels; 0.1 µm interval settings"],
      ["Sampling volume", "10–100 ml"],
      ["Sampling volume error", "Better than ±3%"],
      ["Detection / cleaning speed", "5–60 mL/min (default 25 mL/min)"],
      ["Resolution", "Better than 10%"],
      ["Coincidence error limit", "12,000–40,000 particles/mL"],
      ["Repeatability", "RSD <2%"],
      ["Particle counting error", "±10%"],
      ["Operating temperature", "-20°C to 60°C"],
      ["Storage temperature", "-30°C to 80°C"],
      ["Power supply", "110–240 VAC or 24 VDC"],
    ],
    image: `${base}uskunalar/PC550.png`,
  },
  {
    id: 31,
    name: "VS800 Portable Kinematic Viscometer",
    brand: "SOOHOW",
    model: "VS800",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Portable kinematic viscometer, ASTM D8092, 10–350 cSt @ 40°C",
    badges: ["NEW"],
    desc: "VS800 portable kinematic viscometer measures lubricant kinematic viscosity per ASTM D8092 with accuracy within ±3% of the measured value. Tests virtually any oil sample — clear, dark, or heavily contaminated — without pre-treatment, using only 60 µL per test so lubricant levels are unaffected. Split-cell open-fit capillary cuvette is easy to clean; counter-reflective photoelectric sensors and constant sample temperature during measurement. Portable field design with rechargeable battery — no solvent transport or waste discharge required. Built-in memory stores up to 1000 result groups with USB table export. Applications include petrochemicals, mining, laboratories, and marine shipbuilding.",
    specs: [
      ["Test standard", "ASTM D8092 — kinematic viscosity"],
      ["Viscosity range", "10–350 cSt @ 40°C"],
      ["Measurement temperature", "40°C or 100°C kinematic viscosity; ±0.1°C temperature control"],
      ["Precision", "≤±3% of measured value"],
      ["Repeatability", "RSD ≤±3% (typical)"],
      ["Sample volume", "60 µL (volumetric pipette gun)"],
      ["Sample handling", "No pre-treatment; clear, dark, or contaminated oils"],
      ["Cuvette", "Open-fit capillary cuvette; split-cell; easy wipe cleaning"],
      ["Sensors", "Counter-reflective photoelectric sensors"],
      ["Display", "2.8\" LED; 320 × 240 pixels"],
      ["Input", "4-wire resistive touchscreen"],
      ["Connector", "USB port"],
      ["Software", "Embedded software"],
      ["Data storage", "Built-in memory; up to 1000 groups; USB table export"],
      ["Battery", "24 V; 2600 mAh; rechargeable"],
      ["Power adapter", "DC 24 V power adapter"],
      ["Dimensions (L×W×H)", "201 × 119 × 155 mm"],
      ["Weight", "1.5 kg"],
      ["Applications", "Petrochemicals, mining, laboratories, marine and shipbuilding"],
    ],
    image: `${base}uskunalar/VS800.png`,
  },
  {
    id: 32,
    name: "VS600 Portable Rapid Kinematic Viscometer",
    brand: "SOOHOW",
    model: "VS600",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Rapid kinematic viscometer, 2–2000 mm²/s, auto cycle, portable",
    badges: ["NEW"],
    desc: "VS600 portable rapid kinematic viscometer automates measurement, cleaning, drying, and result calculation in a compact three-proof integrated case. Results in as little as 1 minute (typically within 3 minutes); full cycle from injection to calculation generally under 5 minutes. Measures transparent and opaque Newtonian liquids including gasoline, diesel, kerosene, cutting fluid, heat transfer oil, additives, lubricating oil, and in-use oil. Two viscosity tubes cover a 100× measurement span from 2 to 2000 mm²/s. Quick cleaning uses no more than 10 mL of solution per cycle. Plug-in viscometer replacement in under 10 seconds; guided operation with constant and temperature calibration and heating protection. High-quality lithium battery provides up to 10 hours of operation even at 100°C temperature control. USB data export; optional disposable filters to reduce sample pretreatment. Applications: petrochemicals, mining, laboratories, marine and shipbuilding.",
    specs: [
      ["Standards", "ASTM D7279, D445; NB/SH/T 0956-2017; T/CEC 127-2016"],
      ["Measurement range", "2–2000 mm²/s; dual tubes; 100× span"],
      ["Injection volume", "0.3–1 mL"],
      ["Temperature control", "40–100°C; accuracy ±0.1°C"],
      ["Timing resolution", "0.01 s"],
      ["Repeatability", "≤1%"],
      ["Test time", "As fast as 1 min; typically ≤3 min; full cycle <5 min"],
      ["Automation", "Auto measure, clean, dry, and calculate"],
      ["Cleaning consumption", "Generally ≤10 mL solution per cycle"],
      ["Viscometer replacement", "Plug-in quick swap; ≤10 s"],
      ["Battery", "Li-ion; up to 10 h (including 100°C temp control)"],
      ["Data export", "USB"],
      ["Optional", "Disposable filters for reduced sample pretreatment"],
      ["Overall power", "≤25 W"],
      ["Power supply", "AC 220 V ±10%, 50 Hz ±10%"],
      ["Ambient temperature", "10–28°C"],
      ["Relative humidity", "<80% RH"],
      ["Host size (L×W×H)", "390 × 230 × 300 mm"],
      ["Weight", "Approx. 8 kg"],
      ["Installation", "No strong vibration, airflow, EMI, or corrosive gases"],
      ["Applications", "Petrochemicals, mining, laboratories, marine and shipbuilding"],
    ],
    image: `${base}uskunalar/VS600.png`,
  },
  {
    id: 33,
    name: "DM 100 Density Meter",
    brand: "SOOHOW",
    model: "DM 100",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Portable density meter, ASTM D7777-24, 0–3 g/cm³, IrDA",
    badges: ["NEW"],
    desc: "DM 100 density meter measures liquid density per ASTM D7777-24 in a compact, lightweight handheld design for single-handed operation with an intuitive LED interface. Leak-proof robust housing contains samples even if the sampling pump leaks; the entire pump module is quickly replaceable. U-shaped curved oscillating glass tube cell with automatic pumping or manual injection — 2 mL per sample. Over 20 built-in measurement methods plus 5 customer-defined slots. Stores up to 1024 results with timestamps and sample IDs; USB table export. IrDA infrared interface for printer and PC data transfer. Applications: petrochemicals, chemicals, food and beverage, and electronics engineering.",
    specs: [
      ["Test standard", "ASTM D7777-24"],
      ["Injection", "Automatic pumping or manual injection"],
      ["Sample volume", "2 mL per test"],
      ["Sample cell", "U-shaped curved oscillating glass tube"],
      ["Density range", "0–3 g/cm³"],
      ["Temperature range", "0–40°C (32–104°F)"],
      ["Display", "4-digit 8-segment LED; 55 × 45 × 2.8 mm"],
      ["Resolution", "Density 0.0001 g/cm³"],
      ["Accuracy", "Density ±0.001 g/cm³; temperature ±0.2°C (±0.4°F)"],
      ["Repeatability (SD)", "Density 0.0005 g/cm³; temperature 0.1°C (0.2°F)"],
      ["Reproducibility (SD)", "Density 0.0001 g/cm³"],
      ["Input", "3 metal dome physical buttons"],
      ["Interface", "Infrared (IrDA)"],
      ["Measurement methods", "20+ built-in; 5 user-defined slots"],
      ["Data storage", "Built-in memory; up to 1024 records; USB table export"],
      ["Battery", "2 × AAA (3 V)"],
      ["Dimensions (L×W×H)", "160 × 140 × 28 mm"],
      ["Weight", "Approx. 260 g"],
      ["Applications", "Petrochemicals, chemicals, food & beverage, electronics"],
    ],
    image: `${base}uskunalar/DM%20100.jpg`,
  },
  {
    id: 34,
    name: "JKJQ-1 Insulating Oil Dielectric Strength Tester",
    brand: "SOOHOW",
    model: "JKJQ-1",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Insulating oil BDV tester, 0–80 kV, GB/T 507, touch LCD",
    badges: ["NEW"],
    desc: "JKJQ-1 insulating oil dielectric strength tester performs automatic oil breakdown voltage (BDV) tests per GB/T 507-2002, DL 429.9-91, and DL/T 846.7-2004. A microprocessor controls boosting, holding, stirring, resting, calculation, and printing for dielectric withstand tests from 0 to 80 kV (0–100 kV optional). Large color LCD touchscreen with Chinese and English menus — simple setup for fully automatic operation. Stores breakdown values for 1–10 cycles per test with average, standard deviation, and coefficient of variation; power-off retention for up to 100 results. Uniform 50 Hz voltage rise with overvoltage, overcurrent, and limit protection. Displays ambient temperature, humidity, and system clock. RS232 for PC communication and USB for flash-drive export or barcode scanner. Applications: petrochemicals, electric power, transportation, and railway systems.",
    specs: [
      ["Standards", "GB/T 507-2002; DL 429.9-91; DL/T 846.7-2004"],
      ["Output voltage", "0–80 kV (0–100 kV optional)"],
      ["Distortion rate", "<3%"],
      ["Boost speed", "0.5–5 kV/s (adjustable)"],
      ["Resting time", "15 min (adjustable)"],
      ["Boost interval", "5 min (adjustable)"],
      ["Boost cycles", "1–10 times (optional)"],
      ["Booster capacity", "1.5 kVA"],
      ["Measurement accuracy", "±3%"],
      ["Automation", "Auto boost, hold, stir, rest, calculate, and print"],
      ["Display", "Large color LCD touchscreen; Chinese/English menus"],
      ["Data storage", "1–10 cycles per test; stats; up to 100 results (power-off retained)"],
      ["Voltage control", "Microcontroller; uniform 50 Hz rise"],
      ["Protection", "Overvoltage, overcurrent, and limit protection"],
      ["Ambient display", "Temperature, humidity, and system clock"],
      ["Connectivity", "RS232 (PC); USB (export / barcode scanner)"],
      ["Power supply", "AC 220 V ±10%, 50 Hz ±1 Hz"],
      ["Power consumption", "200 W"],
      ["Operating temperature", "0–45°C"],
      ["Relative humidity", "<75% RH"],
      ["Applications", "Petrochemicals, electric power, transportation, railway"],
    ],
    image: `${base}uskunalar/JKJQ-1.png`,
  },
  {
    id: 35,
    name: "WSKF-201 Karl Fischer Moisture Analyzer",
    brand: "SOOHOW",
    model: "WSKF-201",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Karl Fischer moisture analyzer, 1 ppm–100%, touchscreen",
    badges: ["NEW"],
    desc: "WSKF-201 Karl Fischer moisture analyzer determines water content in petroleum products, organic chemicals, polymer materials, and related samples — especially trace moisture with high precision. Fully automatic operation with automatic drift deduction, automatic result calculation, and USB data acquisition. Fast analysis with results on a touchscreen display; multiple user-defined methods; printable records with operation timestamps. Automatic electrolytic current control up to 400 mA. Applications: petrochemicals, electric power, laboratories, and marine shipbuilding.",
    specs: [
      ["Method", "Karl Fischer moisture analysis"],
      ["Measurement range", "10 µg – 200 mg"],
      ["Water content range", "1 ppm – 100%"],
      ["Maximum measurement speed", "2.24 mg/min"],
      ["Resolution", "0.1 µg"],
      ["Accuracy", "±3 µg (H₂O 10 µg–1000 µg); RSD ≤0.3% (H₂O >1000 µg)"],
      ["Display", "Touchscreen"],
      ["Electrolytic control", "Automatic; up to 400 mA"],
      ["Automation", "Auto drift deduction; auto result calculation"],
      ["Data acquisition", "USB"],
      ["Methods", "Multiple user-defined analysis methods"],
      ["Documentation", "Printable records with operation time"],
      ["Applications", "Petrochemicals, electric power, laboratories, marine and shipbuilding"],
    ],
    image: `${base}uskunalar/WSKF-201.png`,
  },
  {
    id: 36,
    name: "STS-A200 Specific Protein Analyzer",
    brand: "SOOHOW",
    model: "STS-A200",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Specific protein analyzer, ≥180 tests/h, nephelometry, LIS",
    badges: ["NEW"],
    desc: "STS-A200 specific protein analyzer determines specific proteins in human body fluid samples by rate scatter nephelometry or projective turbidimetry. Throughput of at least 180 tests per hour with CV ≤5%, accuracy deviation ≤±5%, carry-over <1%, and stability ≤±5% after 4 and 8 hours. Optical system uses a 12 V long-life halogen lamp with cluster holographic post-splitter technology across 8 wavelengths from 340 to 700 nm. Reaction system with 40 standard UV cups at 37±0.1°C solid direct thermal control. Five-well sample rack with continuous sampling for up to 25 specimens. Ceramic-core micro piston pumps for sample (3–30 µL) and reagent (20–200 µL) dispensing. Built-in scanning, patient management, LIS connectivity, and result printing; automatic warm-water cup cleaning with level detection. Complies with GB/T 14710-2009, GB 4793.1-2007, and GB/T 18268.1-2010. For hospitals, clinics, laboratories, and veterinary use.",
    specs: [
      ["Analytical method", "Rate scatter nephelometry or projective turbidimetry"],
      ["Intended use", "Specific proteins in human body fluid samples"],
      ["Test speed", "≥180 tests per hour"],
      ["Precision (CV)", "≤5%"],
      ["Accuracy (deviation B)", "≤±5% vs stated value"],
      ["Carry-over", "<1%"],
      ["Stability", "≤±5% deviation after 4 h and 8 h operation"],
      ["Sample dispensing", "3–30 µL; accuracy ±5%; CV ≤3%"],
      ["Reagent dispensing", "20–200 µL; accuracy ±5%; CV ≤3%"],
      ["Optical system", "12 V halogen lamp; holographic post-splitter; 8 wavelengths 340–700 nm"],
      ["Reaction system", "40 UV cups; 37±0.1°C; solid direct thermal; maintenance-free sensor"],
      ["Sample rack", "5-well continuous sampling; up to 25 samples"],
      ["Dispensing pump", "Ceramic-core micro piston; high precision; wear-resistant"],
      ["Cleaning", "Automatic warm-water cup wash; auto level detect and report"],
      ["Data processing", "Built-in scan; auto sample info; patient management; LIS; printing"],
      ["Dimensions (max.)", "≤600 × 400 × 520 mm"],
      ["Compliance", "GB/T 14710-2009; GB 4793.1-2007; GB/T 18268.1-2010"],
      ["Applications", "Hospitals, health clinics, laboratories, animal hospitals"],
    ],
    image: `${base}uskunalar/STS-A200.png`,
  },
  {
    id: 37,
    name: "STS-M100 Semi-automatic Specific Protein Analyzer",
    brand: "SOOHOW",
    model: "STS-M100",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Semi-auto protein analyzer, nephelometry, 650 nm, Bluetooth print",
    badges: ["NEW"],
    desc: "STS-M100 semi-automatic specific protein analyzer performs rate scatter nephelometry or projective turbidimetry with a compact footprint for point-of-care and small-lab use. Single-channel detection with manual pipetting and pre-dispensed companion reagents for simple, immediate results. Single-wavelength 650 nm semiconductor light source; automatic temperature control and stirring at reaction vessel position 1. Stores, queries, and prints test results with upload/download and remote upgrade support — up to 20,000 result sets. Real-time multitasking OS with user-friendly Chinese hierarchical menus. Bluetooth printer included. CV ≤5%, accuracy and stability ≤±5% (including after 4 and 8 hours). Complies with GB/T 14710-2009, GB 4793.1-2007, GB 4793.9-2013, YY 0648-2008, and GB/T 18268.1/18268.26-2010. For hospitals, clinics, laboratories, and animal hospitals.",
    specs: [
      ["Analytical method", "Rate scatter nephelometry or projective turbidimetry"],
      ["Measurement channels", "Single channel"],
      ["Precision (CV)", "≤5%"],
      ["Accuracy (deviation B)", "≤±5% vs labeled value"],
      ["Stability", "≤±5% deviation after 4 h and 8 h operation"],
      ["Optical system", "Single-wavelength semiconductor source; 650 nm"],
      ["Reagents", "Companion reagents for analyzers"],
      ["Reaction site", "Reaction vessel position 1"],
      ["Dispensing", "Manual pipetting; pre-dispensed reagents"],
      ["Temperature / stirring", "Automatic temperature control and stirring"],
      ["Data processing", "Store, query, print; upload/download; remote upgrade"],
      ["Storage capacity", "Up to 20,000 test result sets"],
      ["Operating software", "Real-time multitasking OS; Chinese hierarchical menus"],
      ["Peripheral", "Bluetooth printer (standard)"],
      ["Dimensions (max.)", "≤150 × 100 × 70 mm"],
      ["Compliance", "GB/T 14710-2009; GB 4793.1-2007; GB 4793.9-2013; YY 0648-2008; GB/T 18268.1/26-2010"],
      ["Applications", "Hospitals, health clinics, laboratories, animal hospitals"],
    ],
    image: `${base}uskunalar/STS-M100.jpg`,
  },
  {
    id: 38,
    name: "STS-M400 Semi-automatic Specific Protein Analyzer",
    brand: "SOOHOW",
    model: "STS-M400",
    categoryKey: "metalSpectral",
    category: "Industrial Measurement",
    spec: "Semi-auto protein analyzer, 4 ch., 650 nm, Bluetooth print",
    badges: ["NEW"],
    desc: "STS-M400 semi-automatic specific protein analyzer performs rate scatter nephelometry or projective turbidimetry with four measurement channels for higher throughput in clinics and laboratories. Manual pipetting with pre-dispensed companion reagents for simple, immediate results. Single-wavelength 650 nm semiconductor light source; automatic temperature control and stirring at reaction vessel position 1. Stores, queries, and prints test results with upload/download and remote upgrade support — up to 20,000 result sets. Real-time multitasking OS with user-friendly Chinese hierarchical menus. Bluetooth printer included. CV ≤5%, accuracy and stability ≤±5% (including after 4 and 8 hours). Complies with GB/T 14710-2009, GB 4793.1-2007, GB 4793.9-2013, YY 0648-2008, and GB/T 18268.1/18268.26-2010. For hospitals, clinics, laboratories, and animal hospitals.",
    specs: [
      ["Analytical method", "Rate scatter nephelometry or projective turbidimetry"],
      ["Measurement channels", "4 channels"],
      ["Precision (CV)", "≤5%"],
      ["Accuracy (deviation B)", "≤±5% vs labeled value"],
      ["Stability", "≤±5% deviation after 4 h and 8 h operation"],
      ["Optical system", "Single-wavelength semiconductor source; 650 nm"],
      ["Reagents", "Companion reagents for analyzers"],
      ["Reaction site", "Reaction vessel position 1"],
      ["Dispensing", "Manual pipetting; pre-dispensed reagents"],
      ["Temperature / stirring", "Automatic temperature control and stirring"],
      ["Data processing", "Store, query, print; upload/download; remote upgrade"],
      ["Storage capacity", "Up to 20,000 test result sets"],
      ["Operating software", "Real-time multitasking OS; Chinese hierarchical menus"],
      ["Peripheral", "Bluetooth printer (standard)"],
      ["Dimensions (max.)", "≤320 × 230 × 130 mm"],
      ["Compliance", "GB/T 14710-2009; GB 4793.1-2007; GB 4793.9-2013; YY 0648-2008; GB/T 18268.1/26-2010"],
      ["Applications", "Hospitals, health clinics, laboratories, animal hospitals"],
    ],
    image: `${base}uskunalar/STS-M400.png`,
  },
] as Product[];

export const products: Product[] = productCatalog.map((product) => ({
  ...product,
  categoryKey: getProductCategoryKey(product.id),
}));
